### ISSUE TITLE
Please add a web.config file

### ISSUE THREAD

**Issue by aarongustafson** [piwodlaiwo/mapping#1]
We have a template for Node projects: https://a-k-apart.com/webconfigs/web.config.node.txt

**Comment by piwodlaiwo** [comment]
I have added the template file and adjusted the readme and map.js name to index.js. Can this be closed?

**Comment by aarongustafson** [comment]
I’m going to deploy shortly. Will let you know.

**Comment by piwodlaiwo** [comment]
Sounds good, let me know.

**Comment by piwodlaiwo** [comment]
I can see it here (https://a-k-apart.com/gallery/Mapping) so closing
